name: BitBucket Server Migration Tool Windows
on:
  workflow_dispatch:
  
jobs: 
  Get-Repositories-to-Migrate:
    # Specifies the operating system environment on which the workflow will run.
    # In this case, it is set to "ubuntu-latest", which indicates the latest version of Ubuntu.
    runs-on: ubuntu-latest
 
    # CONFIGURE PROJECT MATRIX
    outputs:
      # SET PROJECTS OUTPUT FROM SET-MATRIX STEP
      PROJECTS: ${{ steps.set-matrix.outputs.PROJECTS }}
    
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v3
     
      - name: Set matrix data
        id: set-matrix
        # STORE PROJECTS.JSON INTO PROJECTS VARIABLE
        run: echo "PROJECTS=$(jq -c . < ./projects.json)" >> $GITHUB_OUTPUT
        
  Migration:
    runs-on: [ 'self-hosted' , 'Windows' , 'X64' ]
    needs: Get-Repositories-to-Migrate
    strategy:
      max-parallel: 1
      # SET MATRIX WITH PROJECTS TO MIGRATE
      matrix: ${{ fromJson(needs.Get-Repositories-to-Migrate.outputs.PROJECTS) }}
      
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v3
              
      - name: Migration
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          BBS_USERNAME: ${{ secrets.BBS_USERNAME }}
          BBS_PASSWORD: ${{ secrets.BBS_PASSWORD }}
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          PATH_WORK: ${{ vars.PATH_WORK }}
        
        run: |
          # Obtener la ubicación actual
          $currentLocation = Get-Location
          $currentPath = $currentLocation.Path
          
          # Nombre del archivo JSON
          $jsonFileName = 'projects.json'
          
          # Ruta completa del archivo JSON
          $jsonFilePath = Join-Path $currentPath $jsonFileName
          
          # Verificar la existencia del archivo
          if (Test-Path $jsonFilePath) {
              # Leer el contenido del archivo JSON
              $jsonContent = Get-Content -Raw -Path $jsonFilePath
          
              # Convertir la cadena JSON a un objeto PowerShell
              $projects = $jsonContent | ConvertFrom-Json
          
              # Proyecto específico para el que deseas obtener los repositorios
              $targetProject = "${{ matrix.project }}"
          
              # Búsqueda del proyecto deseado
              $targetProjectInfo = $projects.include | Where-Object { $_.project -eq $targetProject }
          
              if ($targetProjectInfo -ne $null) {
                  # Obtener todos los repositorios del proyecto
                  $repositories = $targetProjectInfo.migrate | ForEach-Object { $_.repositories }
          
                  # Imprimir cada repositorio por separado
                  foreach ($repository in $repositories) {
                      Write-Output $repository
                      Write-Output $env:${{ matrix.project }}              
                      #gh bbs2gh migrate-repo --bbs-server-url https://bitbucket.bice.cl/ --bbs-project ${{ matrix.project }} --bbs-repo $repository
                      $exportOutput = gh bbs2gh migrate-repo --bbs-server-url https://bitbucket.bice.cl/ --bbs-project "${{ matrix.project }}" --bbs-repo $repository
                      $exportId = ($exportOutput | Select-String 'Export ID: (\d+)' -AllMatches).Matches.Groups[1].Value
                      echo "$exportId"
                      $projecto = "${{ matrix.project }}"
                      echo "debug 2"
                      
                      # RETRIEVE FILE TO WORK DIRECTORY
                      gcloud compute scp bitbucket:/var/atlassian/application-data/bitbucket/shared/data/migration/export/Bitbucket_export_$exportId.tar export$exportId.tar --zone "us-central1-a" --project "bice-devsecops"
                      echo "debug 3"
                      
                      # MIGRATE TO GITHUB
                      gh bbs2gh migrate-repo --archive-path ${{ env.PATH_WORK }}\export$exportId.tar --github-org BancoBice --github-repo ${{ matrix.project }}-$repository --bbs-server-url https://bitbucket.bice.cl/ --bbs-project ${{ matrix.project }} --bbs-repo $repository --azure-storage-connection-string "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}"
                      echo "debug final"

                  }
              }
          }
